### PR TITLE
Misc cleanup

### PR DESCRIPTION
**Pull request by greglittlefield-wf**
## Motivation
  
1. When CI fails due to dart2js test failures, it's hard to see the stack of what failed since everything is minified.
2. Our to-do example app doesn't have ignores of ungenerated URIs set up, so it's not a valid representation of what most of our consumers use

## Changes
1. Disable minification in dart2js builds of tests/examples
2. Pull in workiva_analysis_options to ignore ungenerated URI warnings
    - Also remove redundant pedantic lints

## Review
_[See CONTRIBUTING.md][contributing-review-types] for more details on review types (+1 / QA +1 / +10) and code review process._

  

Please review: 

### QA Checklist
- [ ] CI passes (excluding dev build of Dart SDK, which is failing for a known regression)

## Merge Checklist
While we perform many automated checks before auto-merging, some manual checks are needed:
- [ ] A Client Platform member has reviewed these changes
- [ ] There are no unaddressed comments _- this check can be automated if reviewers use the "Request Changes" feature_
- [ ] _For release PRs -_ Version metadata in Rosie comment is correct

[contributing-review-types]: https://github.com/Workiva/over_react/blob/master/CONTRIBUTING.md#review-types
[contributing-manual-testing]: https://github.com/Workiva/over_react/blob/master/CONTRIBUTING.md#manual-testing-criteria

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by sydneyjodon-wk — APPROVED** [review]
+10

**Review by evanweible-wf — APPROVED** [review]

**Review by robbecker-wf — APPROVED** [review]
Looks good!

**Comment by robbecker-wf** [comment]
+10 verified that the analysis errors are not present in 2.7.2 and are in 2.10 so Google can reproduce our.upgrade issues.

**Comment by greglittlefield-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
