### PR TITLE
Finalize changelog for 5.1.0 release

### PR DESCRIPTION
**Pull request by aaronlademann-wf**
## Motivation
The changelog should include all [notable PRs merged since the previous 5.0.1 release](https://github.com/Workiva/over_react/compare/5.0.1...master) that will be included in the 5.1.0 release.

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by sydneyjodon-wk — APPROVED** [review]
+10

**Comment by aaronlademann-wf** [comment]
@Workiva/release-management-pp

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
