### PR TITLE
CPLAT-3974 Remove workaround for DDC bug that is fixed in Dart 2

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Ultimate problem:
There was an emulated function name bug in the Dart Dev Compiler (https://github.com/dart-lang/sdk/issues/27647) that has since been fixed. Our dart2-specific branch of this library no longer needs the workaround for this bug.

## How it was fixed:
Remove the workaround and related code/tests.

## Testing suggestions:
- [ ] CI passes

## Potential areas of regression:
n/a

---

> __FYA:__ @greglittlefield-wf @aaronlademann-wf @kealjones-wk @corwinsheahan-wf

### CODE REVIEW

**Comment by corwinsheahan-wf** [comment]
We need to be sure that this only gets included in the 2.x.x+dart2 release. Dart 1 users will still need this workaround.

**Comment by evanweible-wf** [comment]
@corwin Yup, once 2.0.0-dev is merged into master, master will be considered dart2-only and all dart1 releases and fixes will be based off of a `master_dart1` branch

**Comment by greglittlefield-wf** [comment]
+10

**Comment by greglittlefield-wf** [comment]
@Workiva/release-management-pp

**Pull request merged**
