### PR TITLE
Opt main lib out of react_boilerplate core-check

### PR DESCRIPTION
**Pull request by joebingham-wk**
## Motivation
  
As soon as we set the core check to no longer be dry-run, over_react will fail because there are usages of all the different boilerplate syntaxes. Therefore, we should disable the corecheck to prevent our CIs from failing.

## Changes
  
- Opt out of react_boilerplate core-check

## Review
_[See CONTRIBUTING.md][contributing-review-types] for more details on review types (+1 / QA +1 / +10) and code review process._

  

Please review: 

### QA Checklist
- [ ] Tests were updated and provide good coverage of the changeset and other affected code
- [ ] Manual testing was performed if needed
    - [ ] Steps from PR author: 
        
      - [ ] Verify that the react_boilerplate core-check doesn't run on the root project. Note: it will still run on sub projects with their own pubspecs, but in the core-check summary, it shouldn't include the root project and there should be no failures.
    - [ ] Anything falling under manual testing criteria [outlined in CONTRIBUTING.md][contributing-manual-testing]

## Merge Checklist
While we perform many automated checks before auto-merging, some manual checks are needed:
- [ ] A Client Platform member has reviewed these changes
- [ ] There are no unaddressed comments _- this check can be automated if reviewers use the "Request Changes" feature_
- [ ] _For release PRs -_ Version metadata in Rosie comment is correct

[contributing-review-types]: https://github.com/Workiva/over_react/blob/master/CONTRIBUTING.md#review-types
[contributing-manual-testing]: https://github.com/Workiva/over_react/blob/master/CONTRIBUTING.md#manual-testing-criteria

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by aaronlademann-wf — APPROVED** [review]
+1

**Review by sydneyjodon-wk — APPROVED** [review]
+10

- [x] boilerplate core check doesn't run on root project and there are no failures

**Comment by joebingham-wk** [comment]
🎉 🎉 🎉 

@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
