### PR TITLE
Consume setup-dart 0.2 action

### PR DESCRIPTION
**Pull request by aaronlademann-wf**
[This](https://github.com/dart-lang/setup-dart/pull/10) removes the need for our own local action to specify a Dart version!

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by joebingham-wk — APPROVED** [review]
+10

Changes look good, CI passes (minus dev as expected), and CI ran both stable and 2.7.2!

**Comment by aaronlademann-wf** [comment]
@Workiva/release-management-pp

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
