### PR TITLE
Upgrade built_value_generator to v8

### PR DESCRIPTION
**Pull request by sourcegraph-wk**
## Summary

Client Platform is updating dependencies! Read more details at
https://wiki.atl.workiva.net/display/CP/Dependency+Upgrades

This PR is the last step in the process to upgrade to built_value_generator
v8. At this point, all packages at Workiva are compatible with built_value
v8 and built_collection v5, so this PR upgrades the generator from v7 to v8
and commits the updated assets from it.

Note that because code generated by built_value_generator v8 uses APIs that
are only available in built_value v8 and built_collection v5, this PR also
raises the minimums of those dependencies accordingly.

## TODO

- [x] Run `dart build_runner build` and commit updated generated assets.

## Testing

For most consumers, static analysis along with existing unit and functional
tests should provide adequate coverage of these changes. We are already
using built_value v8 and built_collection v5 in Wdesk; this PR just upgrades
the generated code that uses those libraries to the same version.

---

For more info, reach out to `#support-client-plat` on Slack.

[_Created by Sourcegraph batch change `Workiva/built_value_generator_v8`._](https://sourcegraph.plat.workiva.net/organizations/Workiva/batch-changes/built_value_generator_v8)

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by sourcegraph-wk** [comment]
FYI the build_runner command in the PR description is not quite right, it should be:

```
dart run build_runner build --delete-conflicting-outputs
```

**Comment by todbachman-wf** [comment]
I ran build_runner build in both the root of the package and in the todo_client in the app directory. No files were updated in either locations. I couldn't find any other places there might be built_value code to generate. 🤞

**Review by robbecker-wf — APPROVED** [review]

**Review by greglittlefield-wf — APPROVED** [review]
+10

@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
