### PR TITLE
RED-1195: Create aviary.yaml for over_react

### PR DESCRIPTION
**Pull request by matthewsullivan-wf**
## Description:
Create aviary.yaml for over_react with an empty policy.

## Testing suggestions:
N/A

## Potential areas of regression:
None

---
Please code review and merge if you deem this policy appropriate.  Thanks!

> __FYA:__ @greglittlefield-wf @aaronlademann-wf @jacehensley-wf @clairesarsam-wf @joelleibow-wf

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 1
* Watched file ```aviary.yaml``` added

As a result of the finding(s) listed above, a security review is required for this pull request.

**Comment by matthewlorimor-wf** [comment]
Security +1

**Comment by greglittlefield-wf** [comment]
+1

**Comment by leviwith-wf** [comment]
QA +1

**Comment by colefeisthamel-wf** [comment]
RM +1 manually scanned dependencies

**Pull request merged**
