### PR TITLE
UIP-2091 Release over_react 1.8.0

### PR DESCRIPTION
**Pull request by aaronlademann-wf**
* Fix strong mode warning #54
* Fix issue with `AbstractTransitionComponent` causing components to hang when the `transitionend` event never fires. #55

---

> __FYA:__ @greglittlefield-wf @aaronlademann-wf @jacehensley-wf @clairesarsam-wf @joelleibow-wf

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by greglittlefield-wf** [comment]
@aaronlademann-wf This needs to be a minor bump because of the added `transitionTimeout` API

**Comment by greglittlefield-wf** [comment]
+1

**Comment by jacehensley-wf** [comment]
QA Resource Approval: +1

[x] Dev +1’s on MPR
[x] Dev +1’s present on related CRs
[x] Version info updated
[x] Tests Pass
[x] Rosie run complete/evaluation clean

Ready for merge and tag.

**Pull request merged**
