### PR TITLE
UIP-2138 Release over_react 1.9.0

### PR DESCRIPTION
**Pull request by aaronlademann-wf**
__Improvements__

* #60: Provide easy access to DOM node in `ValidationUtil.warn` messages
* #61: Export some `react` library members and add capturing event handlers
  * Export `setClientConfiguration` and `ReactElement`
  * Export all `Synthetic*Event` classes
  * Add capturing event handlers supported by ReactJS
  

__Bug Fixes__

* #58: Fix issue with the `transitionend` warning (_added via #55_) sometimes firing when it shouldn't
* #59: Ensure `AbstractTransitionComponent` does not call `setState` while in the process of unmounting
  * _Thanks @joshbeam-wf!!!_
* [#65] Work around Dart 1.23 strong mode issue with `MapViewMixin`

---

> __FYA:__ @greglittlefield-wf @jacehensley-wf @clairesarsam-wf @joelleibow-wf

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by greglittlefield-wf** [comment]
+1

**Comment by clairesarsam-wf** [comment]
+1

**Comment by leviwith-wf** [comment]
QA +1

- [X] Dev +1’s on MPR
- [X] Dev +1’s present on related CRs
- [X] Version info updated
- [X] Rosie ran / comment displays expected info
- [X] Dependency Scan Clean

Ready for merge and tag.

**Pull request merged**
