### PR TITLE
Closes #727

### LINKED ISSUE #727: Update app example for test_html_builder v2.2.2
> * Issue Type: BUG
> * `over_react` Version(s): `4.2.6`

The app examples [depends on test_html_builder v2.2.2](https://github.com/Workiva/over_react/blob/master/app/over_react_redux/todo_client/pubspec.yaml#L27), however, the [test templates](https://github.com/Workiva/over_react/tree/master/app/over_react_redux/todo_client/test/unit/_templates) still uses the outdated `{test}` token from test_html_builder version 1. This means that attempting to run unit tests with `pub run build_runner test` will result in the following errors:

```
[SEVERE] test_html_builder:templates on test/unit/browser/redux/models/todo_test.dart:
Test html template must contain exactly one `{{testScript}}` placeholder: test/unit/_templates/react_test_template.html
[SEVERE] test_html_builder:templates on test/unit/browser/redux/models/user_test.dart:
Test html template must contain exactly one `{{testScript}}` placeholder: test/unit/_templates/react_test_template.html
[SEVERE] test_html_builder:templates on test/unit/browser/redux/store_test.dart:
Test html template must contain exactly one `{{testScript}}` placeholder: test/unit/_templates/react_test_template.html
[SEVERE] test_html_builder:templates on test/unit/browser/redux/models/todo_test.dart.browser_test.dart:
Test html template must contain exactly one `{{testScript}}` placeholder: test/unit/_templates/react_test_template.html
[SEVERE] test_html_builder:templates on test/unit/browser/redux/models/user_test.dart.browser_test.dart:
Test html template must contain exactly one `{{testScript}}` placeholder: test/unit/_templates/react_test_template.html
[SEVERE] test_html_builder:templates on test/unit/browser/redux/store_test.dart.browser_test.dart:
Test html template must contain exactly one `{{testScript}}` placeholder: test/unit/_templates/react_test_template.html
[SEVERE] test_html_builder:templates on test/unit/browser/components/app_test.dart:
Test html template must contain exactly one `{{testScript}}` placeholder: test/unit/_templates/react_components_test_template.html
[SEVERE] test_html_builder:templates on test/unit/browser/components/todo_list_item_test.dart:
Test html template must contain exactly one `{{testScript}}` placeholder: test/unit/_templates/react_components_test_template.html
[SEVERE] test_html_builder:templates on test/unit/browser/components/connected_user_list_item_test.dart:
Test html template must contain exactly one `{{testScript}}` placeholder: test/unit/_templates/react_components_test_template.html
[SEVERE] test_html_builder:templates on test/unit/browser/components/connected_todo_list_test.dart:
Test html template must contain exactly one `{{testScript}}` placeholder: test/unit/_templates/react_components_test_template.html
[SEVERE] test_html_builder:templates on test/unit/browser/components/js_interop_test.dart:
Test html template must contain exactly one `{{testScript}}` placeholder: test/unit/_templates/react_components_test_template.html
[SEVERE] test_html_builder:templates on test/unit/browser/components/display_list_test.dart:
Test html template must contain exactly one `{{testScript}}` placeholder: test/unit/_templates/react_components_test_template.html
[SEVERE] test_html_builder:templates on test/unit/browser/components/connected_user_list_test.dart:
Test html template must contain exactly one `{{testScript}}` placeholder: test/unit/_templates/react_components_test_template.html
[SEVERE] test_html_builder:templates on test/unit/browser/components/connected_todo_list_item_test.dart:
Test html template must contain exactly one `{{testScript}}` placeholder: test/unit/_templates/react_components_test_template.html
[SEVERE] test_html_builder:templates on test/unit/browser/components/material_ui_test.dart:
Test html template must contain exactly one `{{testScript}}` placeholder: test/unit/_templates/react_components_test_template.html
[SEVERE] test_html_builder:templates on test/unit/browser/components/create_input_test.dart:
Test html template must contain exactly one `{{testScript}}` placeholder: test/unit/_templates/react_components_test_template.html
[SEVERE] test_html_builder:templates on test/unit/browser/components/todo_list_item_test.dart.browser_test.dart:
Test html template must contain exactly one `{{testScript}}` placeholder: test/unit/_templates/react_components_test_template.html
[SEVERE] test_html_builder:templates on test/unit/browser/components/app_test.dart.browser_test.dart:
Test html template must contain exactly one `{{testScript}}` placeholder: test/unit/_templates/react_components_test_template.html
[SEVERE] test_html_builder:templates on test/unit/browser/components/connected_user_list_item_test.dart.browser_test.dart:
Test html template must contain exactly one `{{testScript}}` placeholder: test/unit/_templates/react_components_test_template.html
[SEVERE] test_html_builder:templates on test/unit/browser/components/connected_todo_list_test.dart.browser_test.dart:
Test html template must contain exactly one `{{testScript}}` placeholder: test/unit/_templates/react_components_test_template.html
[SEVERE] test_html_builder:templates on test/unit/browser/components/js_interop_test.dart.browser_test.dart:
Test html template must contain exactly one `{{testScript}}` placeholder: test/unit/_templates/react_components_test_template.html
[SEVERE] test_html_builder:templates on test/unit/browser/components/display_list_test.dart.browser_test.dart:
Test html template must contain exactly one `{{testScript}}` placeholder: test/unit/_templates/react_components_test_template.html
[SEVERE] test_html_builder:templates on test/unit/browser/components/connected_user_list_test.dart.browser_test.dart:
Test html template must contain exactly one `{{testScript}}` placeholder: test/unit/_templates/react_components_test_template.html
[SEVERE] test_html_builder:templates on test/unit/browser/components/material_ui_test.dart.browser_test.dart:
Test html template must contain exactly one `{{testScript}}` placeholder: test/unit/_templates/react_components_test_template.html
[SEVERE] test_html_builder:templates on test/unit/browser/components/connected_todo_list_item_test.dart.vm_test.dart:
Test html template must contain exactly one `{{testScript}}` placeholder: test/unit/_templates/react_components_test_template.html
[SEVERE] test_html_builder:templates on test/unit/browser/components/connected_todo_list_item_test.dart.browser_test.dart:
Test html template must contain exactly one `{{testScript}}` placeholder: test/unit/_templates/react_components_test_template.html
[SEVERE] test_html_builder:templates on test/unit/browser/components/connected_todo_list_item_test.dart.node_test.dart:
Test html template must contain exactly one `{{testScript}}` placeholder: test/unit/_templates/react_components_test_template.html
[SEVERE] test_html_builder:templates on test/unit/browser/components/create_input_test.dart.browser_test.dart:
Test html template must contain exactly one `{{testScript}}` placeholder: test/unit/_templates/react_components_test_template.html

```

Updating the templates should resolve this error.

---

> __FYI:__ @greglittlefield-wf @aaronlademann-wf @kealjones-wk @evanweible-wf @maxwellpeterson-wf

### PR DESCRIPTION
**Pull request by UnHumbleBen**
## Motivation
See #727 

## Changes
Update html templates in app example for test_html_builder v2.2.2. Checked by running `pub run build_runner test -- -p chrome` in the `app/over_react_redux/todo_client` directory and verifying that the tests can now be loaded and run. 

#### Release Notes
Update html templates in app example for test_html_builder v2.2.2

## Review
_[See CONTRIBUTING.md][contributing-review-types] for more details on review types (+1 / QA +1 / +10) and code review process._

  

Please review: @Workiva/app-framework

### QA Checklist
- [ ] Tests were updated and provide good coverage of the changeset and other affected code
- [ ] Manual testing was performed if needed
    - [ ] Steps from PR author: 
        
    - [ ] Anything falling under manual testing criteria [outlined in CONTRIBUTING.md][contributing-manual-testing]

## Merge Checklist
While we perform many automated checks before auto-merging, some manual checks are needed:
- [ ] A Client Platform member has reviewed these changes
- [ ] There are no unaddressed comments _- this check can be automated if reviewers use the "Request Changes" feature_
- [ ] _For release PRs -_ Version metadata in Rosie comment is correct

[contributing-review-types]: https://github.com/Workiva/over_react/blob/master/CONTRIBUTING.md#review-types
[contributing-manual-testing]: https://github.com/Workiva/over_react/blob/master/CONTRIBUTING.md#manual-testing-criteria

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by evanweible-wf** [comment]
Thank you for this @UnHumbleBen!

**Review by evanweible-wf — APPROVED** [review]

**Review by trentgrover-wf — APPROVED** [review]

**Review by aaronlademann-wf — APPROVED** [review]
+1

@Workiva/release-management-pp

**Comment by chrisgustavsen-wf** [comment]
RM +1

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
