### PR TITLE
WP-5222 UIP-2741 Release over_react 1.18.0

### PR DESCRIPTION
**Pull request by rmconsole-readonly-wk**
Pulls Included in Release:
* [UIP-2742 Improve error message when UiState classes aren't set up properly](https://github.com/Workiva/over_react/pull/117)
* [UIP-2762 More convenient ubiquitous access of DOM/aria props](https://github.com/Workiva/over_react/pull/119)
* [UIP-2751 Transition in/out-specific config, test attributes](https://github.com/Workiva/over_react/pull/120)

Requested by: @jacehensley-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/1.17.0...Workiva:release_over_react_1_18_0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/1.17.0...1.18.0

The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/6449952306233344/logs/)

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
<details>
<summary>Number of Findings: 0</summary>

</details>

**Comment by greglittlefield-wf** [comment]
We need to update CHANGELOG.md, right? I wish we had that step automated...

**Comment by jacehensley-wf** [comment]
Yep, I can push a commit up to do that

**Comment by greglittlefield-wf** [comment]
+1

**Comment by aaronlademann-wf** [comment]
QA +1

- [x] Dev +1's
- [x] All unit tests pass
- [x] Rosie ran/Rosie comment displays expected info
- [x] Dependency Scan Clean

Merging.

**Pull request merged**
