### PR TITLE
Add return types to component boilerplate

### PR DESCRIPTION
**Pull request by timothysteward-wk**
## Motivation
  
When the component boilerplate is copied to a repo with the [`always_declare_return_types`](https://dart-lang.github.io/linter/lints/always_declare_return_types.html) lint enabled, there is an analyzer warning on all the methods without return types.

## Changes
  
Add return types to the component boilerplate.

## Review
_[See CONTRIBUTING.md][contributing-review-types] for more details on review types (+1 / QA +1 / +10) and code review process._

  

Please review: 

### QA Checklist
- [ ] Tests were updated and provide good coverage of the changeset and other affected code
- [ ] Manual testing was performed if needed
    - [ ] Steps from PR author: 
        
    - [ ] Anything falling under manual testing criteria [outlined in CONTRIBUTING.md][contributing-manual-testing]

## Merge Checklist
While we perform many automated checks before auto-merging, some manual checks are needed:
- [ ] A Client Platform member has reviewed these changes
- [ ] There are no unaddressed comments _- this check can be automated if reviewers use the "Request Changes" feature_
- [ ] _For release PRs -_ Version metadata in Rosie comment is correct

[contributing-review-types]: https://github.com/Workiva/over_react/blob/master/CONTRIBUTING.md#review-types
[contributing-manual-testing]: https://github.com/Workiva/over_react/blob/master/CONTRIBUTING.md#manual-testing-criteria

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by joebingham-wk — CHANGES_REQUESTED** [review]
Thanks again for making the changes! It also alerted us to that lint being added to Pedantic.. For record / posterity, and turns out [there's an issue](https://github.com/Workiva/over_react/issues/4430) open around this, which leads to a [Dart linter issue](https://github.com/dart-lang/linter/issues/1901).

The only changes I suggested were around typing `render` as `dynamic`. Reason being (quoting @greglittlefield-wf):
1. because it's exclusively called by the framework and not consumer code, so typing it doesn't provide any value at the call-site
2. because that way you don't have to update the typing when you update render logic to return something different (e.g, an array instead of a ReactElement, a ReactElement instead of a String, etc.)

**Review by joebingham-wk — APPROVED** [review]
+10

@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
