### PR TITLE
RM-111110 Release over_react 4.2.0

### PR DESCRIPTION
**Pull request by aaronlademann-wf**
__The latest version of over_react contains:__

* Add `UiFactory.elementType` convenience getter
* Fix lower bound of the `meta` dependency that was mistakenly set too high in #695

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by greglittlefield-wf — APPROVED** [review]
+10

**Comment by aaronlademann-wf** [comment]
@Workiva/release-management-pp

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
