### PR TITLE
CPLAT-7607 [Dart 1] Improve handling of “repeat” errors thrown from components wrapped by an ErrorBoundary

### PR DESCRIPTION
**Pull request by aaronlademann-wf**
+ Dart 1 port of #350

> See #350 for full description

@greglittlefield-wf @kealjones-wk @joebingham-wk @sydneyjodon-wk

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
The items listed below may not capture all security relevant changes. Before providing a security review, be sure to review the entire PR for security impact.
<details>
<summary>(3) Security relevant changes were detected</summary>
<li>Watched keyword <code>innerHtml</code> in <code>lib/src/component/error_boundary.dart</code> line(s) ['328'] added</li>
<li>Watched keyword <code>InnerHtml</code> in <code>lib/src/component/error_boundary.dart</code> line(s) ['352'] added</li>
<li>Watched keyword <code>dangerouslySetInnerHTML</code> in <code>lib/src/component/error_boundary.dart</code> line(s) ['353'] added</li>
</details>

## Action Items
* Obtain a [security review](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); reviewer should pay special attention to insights listed above
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by maxwellpeterson-wf** [comment]
+1 security
- Our CSP protects us from any potential XSS made possible by this change.

**Comment by greglittlefield-wf** [comment]
+10

**Comment by maxwellpeterson-wf** [comment]
+1 security refresh

**Comment by greglittlefield-wf** [comment]
@Workiva/release-management-p

**Pull request merged**
