### PR TITLE
UIP-2924: Add UiPropsMapView

### PR DESCRIPTION
**Pull request by jacehensley-wf**
## Ultimate problem:
We should add `UiPropsMapView`

## How it was fixed:
- Add and test `UiPropsMapView`

## Testing suggestions:
- Verify tests pass

## Potential areas of regression:
- N/A only new stuff

---
> __FYA:__ @greglittlefield-wf @aaronlademann-wf @jacehensley-wf @clairesarsam-wf @joelleibow-wf

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
<details>
<summary>Number of Findings: 0</summary>

</details>

**Comment by jacehensley-wf** [comment]
Yup, I can create a follow-up ticket

**Comment by greglittlefield-wf** [comment]
When pulled into WSD, I get the following error:
```
error: The name 'UiPropsMixinMapView' is defined in the libraries 'react_util.dart' and 'react_util.dart'. (ambiguous_export at [web_skin_dart] lib/ui_core.dart:12)
```
which causes a bunch of other analyzer errors.

The error message is misleading, since both WSD and over_react files are named `react_util.dart`; the problem is that both lines try to export that class:
```dart
export 'package:over_react/over_react.dart';
export 'src/ui_core/util/react_util.dart';
```

I'm not sure there's a way to export this class in the main over_react entrypoint in a way that's compatible with WSD.

**Comment by aaronlademann-wf** [comment]
+1

**Comment by aaronlademann-wf** [comment]
QA +10

- [x] Testing instruction
- [x] Dev +1's
- [x] Dev/QA +10
- [x] Unit tests created/updated
- [x] All unit tests pass
- [x] Rosie ran/Rosie comment displays expected info
- [x] Dependency Scan Clean

Merging.

**Pull request merged**
