### PR TITLE
Update dart dependencies

### PR DESCRIPTION
**Pull request by sourcegraph-wk**
Summary
---
Frontend Frameworks is updating dependencies! More details at
https://wiki.atl.workiva.net/display/CP/Dependency+Upgrades

```
  # Raise minimums for package versions that we already resolve to
  pubspec_codemod raise-min built_redux 8.0.0 --recursive
  pubspec_codemod raise-min logging 1.0.0 --recursive
  pubspec_codemod raise-min glob 2.0.0 --recursive
  pubspec_codemod raise-min yaml 3.0.0 --recursive
  pubspec_codemod raise-min archive 3.0.0 --recursive
  pubspec_codemod raise-min xml 5.0.0 --recursive

  # allow next versions (io 1 and memoize 3)
  pubspec_codemod raise-max io 2.0.0 --recursive
  pubspec_codemod raise-max memoize 4.0.0 --recursive
   
  # Allow the nullsafe version of intl and color
  pubspec_codemod raise-min intl 0.17.0 --recursive
  pubspec_codemod raise-max intl 0.19.0 --recursive
  pubspec_codemod raise-max color 4.0.0 --recursive
```

A passing CI is sufficient QA (means dependencies resolve and tests run and pass).

For more info, reach out to Rob Becker in `#support-frontend-dx`

[_Created by Sourcegraph batch change `Workiva/update_deps_april_23`._](https://sourcegraph.plat.workiva.net/organizations/Workiva/batch-changes/update_deps_april_23)

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by robbecker-wf — APPROVED** [review]

**Comment by robbecker-wf** [comment]
QA+1 CI passes

**Comment by robbecker-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
