### PR TITLE
CPLAT-6138: Update handler chain utils for dart 2.4 compat

### LINKED ISSUE #304: Doesn't build with latest dart beta
The following code

```dart
typedef Callback1Arg<T1>(T1 arg1);

/// Generic strongly-typed callback chaining utilities for callbacks with one argument.
class CallbackUtil1Arg<T> extends CallbackUtil<Callback1Arg<T>> {
}

abstract class CallbackUtil<TTypedef extends Function> {
  const CallbackUtil();
}
```

now fails with 
```
'T' can't be used contravariantly or invariantly in 'CallbackUtil<dynamic Function(T)>'.
Try not using class type parameters in types of formal parameters of function types.dart(wrong_type_parameter_variance_in_superinterface)
```

Since [This feature](https://github.com/dart-lang/language/blob/master/accepted/future-releases/contravariant-superinterface-2018/feature-specification.md) [landed](https://github.com/dart-lang/sdk/issues/35097)

### PR DESCRIPTION
**Pull request by evanweible-wf**
Closes #304

# [CPLAT-6138](https://jira.atl.workiva.net/browse/CPLAT-6138)
Issue Status

## Motivation
  
When Dart 2.4 is released (imminent), it comes with a small breaking language change that unfortunately affects the handler chaining utils in this package. @greglittlefield-wf and @georgelesica-wf were able to update them in such a way that works around the breaking change without adversely affecting existing usages.

## Changes
  
- The `CallbackUtil` class no longer uses its generic type param (that previously was expected to extend `Function`) and instead explicitly marks the relevant types in the class body as `covariant Function` to achieve the same typing.
- The `CallbackUtilNArg` classes no longer specify a type param when extending `CallbackUtil` since it is unused.
- Run CI on the dart dev channel as well as stable to hopefully illuminate issues like this as early as possible.

Fixes #304 

## Review
_[See CONTRIBUTING.md][contributing-review-types] for more details on review types (+1 / QA +1 / +10) and code review process._

  

Please review: 
@greglittlefield-wf @georgelesica-wf @aaronlademann-wf 

### QA Checklist
- [ ] Tests were updated and provide good coverage of the changeset and other affected code
- [ ] Manual testing was performed if needed
    - [ ] Push up a consumer test PR of this branch in WSD and verify that it passes

## Merge Checklist
While we perform many automated checks before auto-merging, some manual checks are needed:
- [ ] A Client Platform member has reviewed these changes
- [ ] There are no unaddressed comments _- this check can be automated if reviewers use the "Request Changes" feature_
- [ ] _For release PRs -_ Version metadata in Rosie comment is correct

[contributing-review-types]: https://github.com/Workiva/over_react/blob/master/CONTRIBUTING.md#review-types
[contributing-manual-testing]: https://github.com/Workiva/over_react/blob/master/CONTRIBUTING.md#manual-testing-criteria

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by greglittlefield-wf** [comment]
+1 to @evanweible-wf's commits

**Comment by evanweible-wf** [comment]
QA +1
- [x] CI passes
- [x] Dart2 portions of WSD consumer test passed: https://github.com/Workiva/web_skin_dart/pull/1233

**Comment by evanweible-wf** [comment]
+1 to @greglittlefield-wf's commits

**Comment by evanweible-wf** [comment]
@Workiva/release-management-p

**Pull request merged**
