### PR TITLE
WP-5859 UIP-2998 Release over_react 1.20.2

### PR DESCRIPTION
**Pull request by rmconsole-readonly-wk**
Pulls Included in Release:
* [UIP-3039 Get rid of dart2js compiler warnings](https://github.com/Workiva/over_react/pull/137)

Requested by: @aaronlademann-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/1.20.1...Workiva:release_over_react_1_20_2
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/1.20.1...1.20.2

The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/6449952306233344/logs/)

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
<details>
<summary>Number of Findings: 0</summary>

</details>

## Magpie
<details>
<summary>Number of findings: 0</summary>

</details>

**Comment by jacehensley-wf** [comment]
+1 pending CI

**Comment by clairesarsam-wf** [comment]
+1

**Comment by jacehensley-wf** [comment]
QA +1

- [X] Dev +1’s present on related CRs
- [X] Version info updated
- [X] Rosie ran / comment displays expected info
- [X] Dependency Scan Clean

Ready for merge and tag.

**Pull request merged**
