### PR TITLE
RM-176692 RM-176691 Release over_react 4.8.1

### PR DESCRIPTION
**Pull request by rmconsole-readonly-wk**
Pull Requests included in release:
* Patch changes:
	* [FED-681: Add integration docs](https://github.com/Workiva/over_react/pull/800)
	* [Upgrade to platform_detect 2](https://github.com/Workiva/over_react/pull/802)

Requested by: @greglittlefield-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/4.8.0...Workiva:release_over_react_4.8.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/4.8.0...4.8.1

The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/6449952306233344/logs/)
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6449952306233344/?repo_name=Workiva%2Fover_react&pull_number=803)

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by robbecker-wf — APPROVED** [review]

**Comment by autobot-wf** [comment]
Skynet test results failed initially for this build but were approved by rob.becker
https://wf-skynet-hrd.appspot.com/apps/test/smithy/4269428/1
Approval message: 
Dart CI / validate_analyzer (stable, ^1.0.0) (pull_request) Failing after 54s
is known to fail on stable (2.19)

**Comment by robbecker-wf** [comment]
QA+1 @Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
