### PR TITLE
RM-60877 Release over_react 3.0.0+dart1 (stable)

### PR DESCRIPTION
**Pull request by aaronlademann-wf**
This Dart 1 only stable, __major__ release of over_react includes:

### ReactJS 16.x Support

- The underlying `.js` files provided by this package are now ReactJS version `16.10.1`.
- Support for the new / updated lifecycle methods from ReactJS 16 [will be released in version `3.1.0`](https://github.com/Workiva/over_react/milestone/3). __These new lifecycle methods will only be supported in Dart 2.__

> See: [The over_react 3.0.0+dart2 release](https://github.com/Workiva/over_react/pull/408) for more details about breaking changes, etc.

---

🚨 __NOTE: This will be the last release of over_react that supports the Dart 1 SDK.__   🚨

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by aaronlademann-wf** [comment]
Semver +1

**Comment by greglittlefield-wf** [comment]
Semver +1

**Comment by greglittlefield-wf** [comment]
+10

**Comment by aaronlademann-wf** [comment]
@Workiva/release-management-pp

**Pull request merged**
