### PR TITLE
CPLAT-4646: Add empty `$` prefixed props mixins for backwards compatible consumers

### PR DESCRIPTION
**Pull request by corwinsheahan-wf**
## Ultimate problem:
Over react 2.x+dart2 is using the Dart 2 only compatible boilerplate, since it does not have to be Dart 1 compatible. However, consumers who have been codemodded with backwards compatible over_react boilerplate will expect `$` prefixed props/state mixins to be exported from over_react. 

## How it was fixed:
Add empty `$` prefixed mixins for Props mixin (there are no state mixins).

## Testing suggestions:
* CI Passes

## Potential areas of regression:
None

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by corwinsheahan-wf** [comment]
CI is gonna fail on this until we get #252 merged in, as it contains a fix for the hint causing CI to fail

**Comment by smaifullerton-wk** [comment]
QA +1 CI passes

**Comment by olesiathoms-wk** [comment]
+10 CI Passes

**Comment by corwinsheahan-wf** [comment]
@Workiva/release-management-p

**Pull request merged**
