### PR TITLE
UIP-2434 Release over_react 1.13.0

### PR DESCRIPTION
**Pull request by aaronlademann-wf**
__Dependency Updates__

* #89: quiver `>=0.21.4 <0.26.0` (was `>=0.21.4 <0.25.0`)

__New Features__

* #87: Make `DomProps`/`SvgProps` implement `UiProps` for more convenient DDC typing

__Misc__

* #86: Get tests passing using the DDC
* #83: Use `over_react_test`

---

> __FYA:__ @greglittlefield-wf @aaronlademann-wf @jacehensley-wf @clairesarsam-wf @joelleibow-wf

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 0

**Comment by greglittlefield-wf** [comment]
+1

**Comment by clairesarsam-wf** [comment]
+1

**Comment by leviwith-wf** [comment]
QA +1

- [X] Dev +1’s on MPR
- [X] Dev +1’s present on related CRs
- [X] Version info updated
- [X] Rosie ran / comment displays expected info
- [X] Dependency Scan Clean

Ready for merge and tag.

**Pull request merged**
