### PR TITLE
RM-132104 RM-132103 Release over_react 4.2.8

### PR DESCRIPTION
**Pull request by rmconsole-readonly-wk**
Pull Requests included in release:
* Patch changes:
	* [Upgrade built_value_generator to v8](https://github.com/Workiva/over_react/pull/729)

Requested by: @greglittlefield-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react/compare/4.2.7...Workiva:release_over_react_4.2.8
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react/compare/4.2.7...4.2.8

The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/6449952306233344/logs/)
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6449952306233344/?pull_number=732&repo_name=Workiva%2Fover_react)

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by greglittlefield-wf — APPROVED** [review]
+10

**Comment by robbecker-wf** [comment]
QA+1 CI Passes - We're ok with the analyzer plugin failing on the dev branch

**Review by robbecker-wf — APPROVED** [review]

**Comment by greglittlefield-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
