### PR TITLE
Analyzer plugin jam integration

### PR DESCRIPTION
**Pull request by greglittlefield-wf**
## Motivation
We did a bunch of work on the analyzer plugin, and it's time to release it!

### Changes from changelog:

- Fix diagnostics not working in Dart >=2.13, by upgrading to analyzer_plugin 0.6.0
- Diagnostics can be configured with custom severity, including disabling them ([docs](https://github.com/Workiva/over_react/blob/master/tools/analyzer_plugin/README.md#configuration))
- New diagnostics:
    - `over_react_create_ref_usage` - Warns when using createRef in a function component instead of useRef
    - `over_react_non_defaulted_prop` - Warns when using a prop in a function component instead of a local variable that defaults the prop
    - `over_react_rules_of_hooks` - Warns when calling hooks conditionally or using hooks outside of function components or custom hook functions
    - `over_react_style_camel_case` - Warns when using non-camelCased keys in `style` maps, which get ignored by React
- New assists:
  - Convert between function and class component syntax (only moves code around and doesn't migrate lifecycle methods, state, hooks, etc.)
- Improvements to existing features:
    - `over_react_invalid_render_return_type` - Update to work with function components
    - `over_react_duplicate_prop_cascade` - Fix duplicate DOM props not linting in certain cases
    - "Add ref" assist and ref object quick fixes - Update to work with function components
- Migrate most code to null safety, fix several potential null errors
- Improve test coverage

### Other changes
- Update `FluentComponentUsage` implementation with the latest from `over_react_codemod`
- Handle more cases in ConstantEvaluator
- Consolidate package:over_react imports into a single place, trim down imports to just boilerplate parsing APIs
- Test infrastructure maintenance/improvements
- Disable AnalyzerDebugHelper by default
- Share computation of `FluentComponentUsage`s between diagnostics for a given file
- Add WIP code for exhaustive dependencies (useEffect, useCallback, etc.) diagnostic

## Review
_[See CONTRIBUTING.md][contributing-review-types] for more details on review types (+1 / QA +1 / +10) and code review process._

  

Please review: 

### QA Checklist
- [ ] Tests were updated and provide good coverage of the changeset and other affected code
- [ ] Manual testing was performed if needed
    - [ ] Steps from PR author: 
        
    - [ ] Anything falling under manual testing criteria [outlined in CONTRIBUTING.md][contributing-manual-testing]

## Merge Checklist
While we perform many automated checks before auto-merging, some manual checks are needed:
- [ ] A Client Platform member has reviewed these changes
- [ ] There are no unaddressed comments _- this check can be automated if reviewers use the "Request Changes" feature_
- [ ] _For release PRs -_ Version metadata in Rosie comment is correct

[contributing-review-types]: https://github.com/Workiva/over_react/blob/master/CONTRIBUTING.md#review-types
[contributing-manual-testing]: https://github.com/Workiva/over_react/blob/master/CONTRIBUTING.md#manual-testing-criteria

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by kealjones-wk — COMMENTED** [review]
I didn't look at any of this but im sure its fine. LGTM

**Comment by kealjones-wk** [comment]
+9

**Review by aaronlademann-wf — APPROVED** [review]
+1 !!!

**Comment by greglittlefield-wf** [comment]
@aaronlademann-wf There's a Dart bug that prevents diagnostics from running in command line tools like `dart analyze` or `tuneup` (see [here](https://github.com/Workiva/over_react/tree/analyzer-plugin-jam-base/tools/analyzer_plugin#:~:text=Note%20that%2C%20currently%2C%20diagnostics%20only%20show%20up%20in%20your%20IDE%2C%20and%20not%20in%20command%20line%20tools) for more info), so I don't believe releasing this should impact any existing consumer's CI.

**Review by aaronlademann-wf — APPROVED** [review]
+10

**Comment by greglittlefield-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
