### PR TITLE
CPLAT-1053 Cancel the transitionend timer when AbstractTransitionComponent unmounts

### PR DESCRIPTION
**Pull request by aaronlademann-wf**
+ To prevent ReactJS setState warnings involving unmounted components

## Motivation
ReactJS `setState` warnings are being produced by components that extend from `AbstractTransitionComponent`.

## Changes
Cancel the `transitionend` timer in-addition-to the subscription within `componentWillUnmount`.

#### Release Notes
Fix issue that causes ReactJS `setState` warnings to appear in the browser console.

## Review
_[See CONTRIBUTING.md][contributing-review-types] for more details on review types (+1 / QA +1 / +10) and code review process._

  

Please review: @greglittlefield-wf 

### QA Checklist
- [ ] Tests were updated and provide good coverage of the changeset and other affected code
- [ ] Manual testing was performed if needed
    - [ ] Steps from PR author: 
        
    - [ ] Anything falling under manual testing criteria [outlined in CONTRIBUTING.md][contributing-manual-testing]

## Merge Checklist
While we perform many automated checks before auto-merging, some manual checks are needed:
- [ ] A Client Platform member has reviewed these changes
- [ ] There are no unaddressed comments _- this check can be automated if reviewers use the "Request Changes" feature_
- [ ] _For release PRs -_ Version metadata in Rosie comment is correct

[contributing-review-types]: https://github.com/Workiva/over_react/blob/master/CONTRIBUTING.md#review-types
[contributing-manual-testing]: https://github.com/Workiva/over_react/blob/master/CONTRIBUTING.md#manual-testing-criteria

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by greglittlefield-wf** [comment]
+1

**Comment by greglittlefield-wf** [comment]
+1

**Comment by aaronlademann-wf** [comment]
QA +1

@Workiva/release-management-pp

**Pull request merged**
