### PR TITLE
Bump minimum sdk version from 1.17.1 to 1.19.1

### PR DESCRIPTION
**Pull request by aaronlademann-wf**
## Ultimate problem:
Dart SDK version 1.19.1 introduces the ability to have trailing commas in argument lists, which will make re-ordering components in our fluent style much less error-prone for consumers.

It also removes the need for a couple of gross type casts we were doing in #15.

## How it was fixed:
Updated the sdk constraint in `pubspec.yaml`, `integrate/pubspec.yaml`, and in the Travis CI configuration.

## Testing suggestions:
Verify that all tests pass.

## Potential areas of regression:
None expected.

---

> __FYA:__ @greglittlefield-wf @aaronlademann-wf @jacehensley-wf @clairesarsam-wf @joelleibow-wf

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 0

**Comment by greglittlefield-wf** [comment]
+1

**Comment by aaronlademann-wf** [comment]
@leviwith-wf this is ready for QA + Merge

**Comment by leviwith-wf** [comment]
QA +10
 
- [X] Testing instruction
- [X] Dev +1's
- [X] Dev/QA +10
- [X] All unit tests pass

Merging.

**Comment by colefeisthamel-wf** [comment]
RM +1 manually reviewed dependencies

**Pull request merged**
